### ISSUE TITLE
Clarity on 'reproduce'

### ISSUE THREAD

**Issue by krista-bradshaw** [ielab/IR-Superproject-2023#11]
When reproducing the original study, I understand this means doing the exact same method. I am reproducing "Evaluating the Robustness of Retrieval Pipelines with Query Variation Generators" and I was hoping for some guidance on what it means to reproduce aspects of their work.
1. Their study begins by sampling the UQV100 dataset and doing a card sort to determine the 6 types of query variations - do I also need to do this or do I just use the 6 variations they suggest?
2. They create 10 methods to automatically generate query variations - should I be creating my own versions of these or using exactly theirs (i.e. their code)?

**Comment by Karlywang** [comment]
Hi Krista,

For now, you can follow the original study, i.e., using the same 6 variations (they actually only choose 4 of them), and using exactly their query variation generations. After you successfully replicate their experiments (results), we can discuss more possible extensions.
