### ISSUE TITLE
error on train_rodr_dpr.sh

### ISSUE THREAD

**Issue by ncdg-misaki** [ielab/IR-Superproject-2023#12]
For my thesis project, I chose to reproduce the second paper: Towards Robust Dense Retrieval via Local Ranking Alignment. But it seems to be an experiment in Linux. And I tried to reproduce it in Windows, and I encountered many problems during the reproduction process. Is it necessary to run this project in Linux, and can I be sure that I can reproduce it successfully in Windows?
The problem I am currently experiencing is that:
I have modified the code to make it work on Windows, but the following error is reported. Are there any problems with the code itself? As this is not a popular paper and not many people have tried it, it is difficult for me to find a suitable solution without an issue being raised and discussed.
 
![image](https://user-images.githubusercontent.com/62094172/236754830-7e2ca4b0-af53-4763-88fe-881a7f96f87a.png)
![image](https://user-images.githubusercontent.com/62094172/236754902-cd9588b2-5a10-460c-8929-0808d0749743.png)
![image](https://user-images.githubusercontent.com/62094172/236754914-65696445-e93b-44db-af2b-18e46d8d3a12.png)

**Comment by Karlywang** [comment]
Hi.

For the first question,
You can try to run the experiments without a GPU, for example, your Windows local machine.
Or for GPU resources, you can try to access [Rangpur Cluster](https://student.eait.uq.edu.au/infrastructure/compute/) and [Google colab](https://colab.research.google.com/).

For the second question,
Can you provide more information about the error?
