### ISSUE TITLE
Running platform

### ISSUE THREAD

**Issue by Manyanggg** [ielab/IR-Superproject-2023#13]
Dear @guidozuc  

I wanted to follow up on something you mentioned in our group meeting a few weeks ago. You had mentioned providing some software to assist us with our projects, and I was wondering if there have been any updates or progress on this? It would be really helpful to have that tool available, so I just wanted to check in and see if there's any news. Thank you! 

Regards.

**Comment by Karlywang** [comment]
Hi @Manyanggg, for computation resources, can you try Rangpur Cluster? 

Here is the documentation: [Rangpur Cluster](https://student.eait.uq.edu.au/infrastructure/compute/)

You can also get GPU from [Google colab](https://colab.research.google.com/)
