### ISSUE TITLE
template for writing a proposal draft 

### ISSUE THREAD

**Issue by guidozuc** [ielab/IR-Superproject-2023#3]
A question received via email:

```
Do you have a template for writing a proposal draft , I would like to refer to it, thank you.
 
Yours sincerely
 
Shihuai
```

**Comment by guidozuc** [comment]
You can find example proposals at [https://iteethesis-examples.uqcloud.net/search](https://iteethesis-examples.uqcloud.net/search)
You should consider only those that are related to this area, e.g. Information Retrieval, Machine Learning, Deep Learning. Relevant example proposals: On the Efficiency and Accuracy of On-Device Recommendation Systems


A typical structure would be like:
1. Abstract
2. Background and literature review
3. Project Plan
4. References

**Comment by tzralice** [comment]
Hi, seems like this link is not working https://iteethesis-examples.uqcloud.net/search. 
To pass the draft proposal, do we need to write it in full paragraph or dot pots are also acceptable?

**Comment by guidozuc** [comment]
Strange: I just tried also from outside the UQ network and it works.
In any case, here is the example I mentioned.

For the draft proposal, I suggest to write full paragraph or in alternative **well elaborated** bullet points.

[Proposal_46995636.pdf](https://github.com/ielab/IR-Superproject-2023/files/11039782/Proposal_46995636.pdf)
