### ISSUE TITLE
Draft Feedback

### ISSUE THREAD

**Issue by krista-bradshaw** [ielab/IR-Superproject-2023#7]
When can we be expecting feedback/marks for our draft proposal submission? It seems that the due date for resubmission was today and the final due date is soon, however I haven't received any feedback yet - do we need to book a meeting with you?

**Comment by Karlywang** [comment]
Hi,

We will give feedback by the end of this week.

**Comment by krista-bradshaw** [comment]
@Karlywang @guidozuc 
Hi,

Just wanted to follow up on this as I still haven't received any feedback and the final submission due date is very soon - Thanks

**Comment by guidozuc** [comment]
Hi, they should all be in the system now
