### ISSUE TITLE
Question of Project Direction

### ISSUE THREAD

**Issue by yyj888** [ielab/IR-Superproject-2023#8]
Dear Prof. Guido Zuccon

For the research direction of 'Reproduce the pape', I would like to know if reproduce  means using the same database and methods as the author to validation/compare the author's result. Do we need to do futher work?

Thanks.

**Comment by Karlywang** [comment]
Hi,

Yes. The reproduction means you use the same methods and experimental settings to see if you can replicate what the authors reported in the original paper.

After you reproduce the paper, you can continue the expansion of the original experiment to other settings like datasets/evaluation metrics/parameters/etc - to show whether the method generalise, or to explore a direction that was not considered in the original work.
